"""waitlist table

Revision ID: 0708b29f95f8
Revises: 
Create Date: 2025-06-14 12:46:35.228452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0708b29f95f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlists_email'), 'waitlists', ['email'], unique=True)
    op.create_index(op.f('ix_waitlists_id'), 'waitlists', ['id'], unique=False)
    op.create_index(op.f('ix_waitlists_name'), 'waitlists', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlists_name'), table_name='waitlists')
    op.drop_index(op.f('ix_waitlists_id'), table_name='waitlists')
    op.drop_index(op.f('ix_waitlists_email'), table_name='waitlists')
    op.drop_table('waitlists')
    # ### end Alembic commands ###
