"""remove first_name in  waitlist table

Revision ID: 372e410b1048
Revises: 542b8593791c
Create Date: 2025-06-14 16:22:05.431499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372e410b1048'
down_revision: Union[str, None] = '542b8593791c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlists_first_name'), table_name='waitlists')
    op.drop_column('waitlists', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlists', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_waitlists_first_name'), 'waitlists', ['first_name'], unique=False)
    # ### end Alembic commands ###
