"""update waitlist table

Revision ID: 542b8593791c
Revises: 0708b29f95f8
Create Date: 2025-06-14 15:04:20.884052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542b8593791c'
down_revision: Union[str, None] = '0708b29f95f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlists', sa.Column('first_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_waitlists_first_name'), 'waitlists', ['first_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlists_first_name'), table_name='waitlists')
    op.drop_column('waitlists', 'first_name')
    # ### end Alembic commands ###
